---
name: "distill"
output_dir: "_site"
title: ""
navbar:
  right:
    - text: "Riders"
      href: https://www.lavuelta.es/en/riders
    - text: "Route"
      href: https://www.lavuelta.es/en/overall-route
  left:
    - text: "Results"
      href: 
      menu:
        - text: "Stage 1"
          href: stage-1.html
    - text: "Teams"
      href: Teams.html
    - text: "Rules"
      href: Rules.html
          
    - icon: logo.png
      href: https://github.com/rstudio/distill
output:
distill::distill_article:
  css: styles.css

---
