---
name: "distill"
output_dir: "_site"
title: ""
navbar:
  right:
    - text: "Riders"
      href: https://www.lavuelta.es/en/riders
    - text: "Route"
      href: https://www.lavuelta.es/en/overall-route
  left:
    - text: "Results"
      href: 
      menu:
        - text: "Stage 1"
          href: stage-1.html
        - text: "Stage 2"
          href: stage-2.html
        - text: "Stage 3"
          href: stage-3.html
        - text: "Stage 4"
          href: stage-4.html
        - text: "Stage 5"
          href: stage-5.html
        - text: "Stage 6"
          href: stage-6.html
        - text: "Stage 7"
          href: stage-7.html
        - text: "Stage 8"
          href: stage-8.html
        - text: "Stage 9"
          href: stage-9.html
        - text: "Stage 10"
          href: stage-10.html
        - text: "Stage 11"
          href: stage-11.html
        - text: "Stage 12"
          href: stage-12.html
        - text: "Stage 13"
          href: stage-13.html
        - text: "Stage 14"
          href: stage-14.html
        - text: "Stage 15"
          href: stage-15.html
    - text: "Standings"
      href:
      menu:
        - text: "Points Standings"  
          href: Current_overall.html
        - text: "Points Standings"  
          href: Current_points.html
    - text: "Teams"
      href: Teams.html
    - text: "Rules"
      href: Rules.html
          
    - icon: logo.png
      href: https://github.com/rstudio/distill
      
output:
distill::distill_article:
  css: styles.css

---
