---
name: "distill"
output_dir: "_site"
title: ""
navbar:
  right:
    - text: "Riders"
      href: https://www.lavuelta.es/en/riders
    - text: "Route"
      href: https://www.lavuelta.es/en/overall-route
  left:
    - text: "Results"
      href: 
      menu:
        - text: "Stage 1"
          href: stage-1_2025-08-15.html
        - text: "Stage 2"
          href: stage-2_2025-08-15.html
        - text: "Stage 3"
          href: stage-3_2025-08-15.html
        - text: "Stage 4"
          href: stage-4_2025-08-15.html  
        - text: "Stage 5"
          href: stage-5_2025-08-15.html 
    - text: "Rules"
      href: Rules.html
          
    - icon: logo.png
      href: https://github.com/rstudio/distill
output: distill::distill_article
---